### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [pivotal-cf-experimental/cron-resource#9]
Hi Team,

I am trying to use “**cron-resource**” over ARM64v8 but it seems it does not have an arm64 supported tag in docker hub.

I have successfully built the image using the command “**docker build -t <image_name> .**” and used it successfully on arm64 platform.

Do you have any plans for releasing an ARM64 image?

May I know how the amd64 image is getting published on Dockerhub?

It will be very helpful if the image is released with ARM64 support. To start with can I get suggestions on which CI you are using to push the image to Dockerhub.

**Comment by rowanjacobs** [comment]
We use [Concourse](https://concourse-ci.org) with the [docker-image resource](https://github.com/concourse/docker-image-resource) to build the image. We don't currently have plans to release an ARM64 image, and the team that maintains this image does not do very much active work on it so your best bet may be to fork the image. But if you want to pair on this I would be willing to help you get it done. Out of curiosity, what are you trying to do?

**Comment by rowanjacobs** [comment]
Here is the job config we are using to build the image:
```
  - name: update-cron-resource-image
    build_logs_to_retain: 25
    serial: true
    plan:
    - get: cron-resource_image
      tags: [gcp]
      params:
        save: true
    - put: archived_cron-resource_image
      tags: [gcp]
      params:
        load: cron-resource_image
    - get: cron-resource-dockerfile
      tags: [gcp]
      trigger: true
    - put: cron-resource_image
      tags: [gcp]
      params:
        build: cron-resource-dockerfile
        dockerfile: cron-resource-dockerfile/Dockerfile
```
